@echo off
echo Instalando matplotlib...
pip install matplotlib
echo Instalando cython...
pip install cython
echo Instalando Kivy...
pip install kivy
echo Instalando MD...
pip install kivymd
echo Dependencias instaladas para editar el programa
pause